# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/f0b96e4b-4822-4d15-b314-2f9fa2587b5b";
    fsType = "btrfs";
    options = [ "subvol=root" ];
  };

  #boot.initrd.luks.devices."NixOS".device = "/dev/disk/by-uuid/182fcd31-011d-43d5-8ba6-51c65f65aebc";

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/f0b96e4b-4822-4d15-b314-2f9fa2587b5b";
    fsType = "btrfs";
    options = [ "subvol=nix" ];
  };

  #fileSystems."/boot" = {
  #  device = "/dev/disk/by-uuid/ba2b7318-3fac-4452-9fce-554628c6e3d2";
  #  fsType = "btrfs";
  #};

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/4035-B369";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  #fileSystems."/media" = {
  #  device = "/dev/mapper/gms";
  #  fsType = "btrfs";
  #  options = [ "subvol=main" ];
  #};

  #boot.initrd.luks.devices."games".device = "/dev/disk/by-uuid/7374899f-0686-47ee-b50c-4befe77a75d2";
  #boot.initrd.luks.devices."swap".device = "/dev/disk/by-uuid/87840706-1153-4fb8-8b24-64cbed77da30";

  swapDevices = [
    #{ device = "/dev/mapper/swap"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
