[book]
title = "SkyOS Documentation"
authors = ["Sk7Str1p3"]
description = "Documentation for Sk7Str1p3's custom NixOS configuration"
language = "en"

[output.html]
additional-css = ["./theme/catppuccin.css"]
